apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: server
spec:
  type: {{ .Values.services.server.type }}
  {{- if and (eq .Values.services.server.type "LoadBalancer") .Values.services.server.loadbalancer.ip }}
  loadBalancerIP: {{ .Values.services.server.loadbalancer.ip }}
  {{- end }}
  ports:
    - port: {{ if eq (toString .Values.applications.server.env.HTTPS) "1" }}443{{ else }}80{{ end }}
      targetPort: {{ if eq (toString .Values.applications.server.env.HTTPS) "1" }}443{{ else }}80{{ end }}
  selector:
    app.kubernetes.io/name: server
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: mysql
spec:
  type: {{ .Values.services.mysql.type }}
  {{- if and (eq .Values.services.mysql.type "LoadBalancer") .Values.services.mysql.loadbalancer.ip }}
  loadBalancerIP: {{ .Values.services.mysql.loadbalancer.ip }}
  {{- end }}
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/name: mysql
